services:
  unitree_dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: unitree_dev
    network_mode: host        # REQUIRED
    privileged: true          # REQUIRED
    gpus: all
    shm_size: "1gb"
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.docker.xauth:ro
    tty: true
